services:
  app:
    build:
      context: .
    container_name: rag-bootcamp-app
    env_file:
      - .env
    ports:
      - "8012:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  cli:
    profiles:
      - cli
    build:
      context: .
    container_name: rag-bootcamp-cli
    env_file:
      - .env
    volumes:
      - .:/app
    command: python CLI.py
    stdin_open: true
    tty: true
